[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "text/javascript"

[[headers]]
  for = "/*.jsx"
  [headers.values]
    Content-Type = "text/javascript"

[build]
  publish = "dist"
  command = "npm run build"